title:            'bytel00m blog'
description:      'Marek Mierzwa - dev & other stuff'
# put your disqus here
disqus_shortname: bytel00mbloggithubpages
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             # logo visible in the topbar
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: http://byteloom.marek-mierzwa.com
feed_url: http://feeds.feedburner.com/Bytel00mBlog

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'main'
    url: '/'
  - title: 'about'
    url: '/about'
  - title: 'tags'
    url: '/tags'
#  - title: 'categories'
#    url: '/categories'
#    type: 'categories'
#    submenu:
#      - title: 'mobile'
#      - title: 'developers life'
#      - title: 'enterprise search'

# Owner/author information
owner:
  name:           Marek Mierzwa
  site:           http://www.marek-mierzwa.com
  avatar:         images/marekmierzwa_small.png
  bio:            "Husband, father, spiritual journeyman and in the meantime a software developer"
  email:          contact@marek-mierzwa.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: MarekMierzwa # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: mmierzwa

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/mmierzwa"
  - title: "linkedin"
    url: "https://pl.linkedin.com/in/marek-mierzwa-13575a26"
#  - title: "youtube"
#    url: "https://www.youtube.com/channel/..."
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-77336188-1
google_verify: tIKtPGZmvX3yzfBwbwKqyT-ueu3F4QUgHvLfmrOOMBo
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: DFE18A7DA629947848B0673582CE3E86

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Warsaw
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
gems:
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
#  enable_coderay: true

  syntax_highlighter: rogue
#  syntax_highlighter_opts:
#    line_numbers: nil
#    line_numbers_start: 1
#    tab_width: 4
#    bold_every: 10
#    css: class

# Octopress
# Default extensions
# post_ext: md
# page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "*.*proj", "*.sln", "project.json", "*.user"]
gems: [jekyll-paginate]
